version: "3"

services:
  app:
    container_name: picsio-app
    restart: unless-stopped
    image: ppicsio-app:latest
    build:
      context: .
    ports:
      - 3000:3000
  mongo:
    container_name: mongo_db
    image: mongo:7.0.0
    ports:
      - "27017:27017"
    volumes:
      - ./docker/volume/mongodb:/data/db
